# PLG — interactive Supabase setup for desktop + cloud API
# Run: powershell -ExecutionPolicy Bypass -File scripts\setup_supabase.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
$SqlFile = Join-Path $Root "cloud\supabase\setup_all.sql"

Write-Host ""
Write-Host "=== PLG Supabase Setup ===" -ForegroundColor Cyan
Write-Host ""

if (-not (Test-Path $SqlFile)) {
    Write-Host "ERROR: Missing $SqlFile" -ForegroundColor Red
    exit 1
}

Write-Host "Step 1 — Create a Supabase project" -ForegroundColor Yellow
Write-Host "  https://supabase.com/dashboard → New project"
Write-Host "  Region: EU (Frankfurt) recommended for GDPR"
Write-Host ""

Write-Host "Step 2 — Run database schema" -ForegroundColor Yellow
Write-Host "  Dashboard → SQL Editor → New query"
Write-Host "  Paste contents of:"
Write-Host "    $SqlFile"
Write-Host "  Click Run (green). Should finish without errors."
Write-Host ""

Write-Host "Step 3 — Auth settings (dev)" -ForegroundColor Yellow
Write-Host "  Authentication → Providers → Email: ON"
Write-Host "  Authentication → Settings → disable 'Confirm email' for local dev"
Write-Host ""

Write-Host "Step 4 — Copy API keys" -ForegroundColor Yellow
Write-Host "  Project Settings → API:"
Write-Host "    Project URL          → SUPABASE_URL"
Write-Host "    anon public          → SUPABASE_ANON_KEY (desktop)"
Write-Host "    service_role secret  → SUPABASE_SERVICE_KEY (server only)"
Write-Host "    JWT Secret           → SUPABASE_JWT_SECRET (server only)"
Write-Host ""

function Read-Required([string]$Prompt) {
    do {
        $v = Read-Host $Prompt
        $v = $v.Trim()
    } while (-not $v)
    return $v
}

$url = Read-Required "SUPABASE_URL (https://xxx.supabase.co)"
$anon = Read-Required "SUPABASE_ANON_KEY"
$service = Read-Required "SUPABASE_SERVICE_KEY"
$jwt = Read-Required "SUPABASE_JWT_SECRET"

# Optional: reuse Gemini key from root .env for cloud API
$gemini = ""
$rootEnv = Join-Path $Root ".env"
if (Test-Path $rootEnv) {
    foreach ($line in Get-Content $rootEnv) {
        if ($line -match '^\s*GEMINI_API_KEY=(.+)$') {
            $gemini = $Matches[1].Trim()
            break
        }
    }
}
if (-not $gemini) {
    $gemini = Read-Host "GEMINI_API_KEY (for cloud API beat generation)"
}

# --- cloud/.env ---
$cloudEnv = Join-Path $Root "cloud\.env"
$cloudContent = @"
# Generated by scripts/setup_supabase.ps1 — do not commit

SUPABASE_URL=$url
SUPABASE_SERVICE_KEY=$service
SUPABASE_JWT_SECRET=$jwt

PLG_LLM_PROVIDER=gemini
GEMINI_API_KEY=$gemini

PLG_BEAT_LIMIT=30
PLG_BEAT_PERIOD_DAYS=30
PLG_DAILY_BEAT_LIMIT=3
PLG_MAX_DEVICES=3
PLG_TRIAL_BEATS=3
PLG_GRACE_DAYS=3

PLG_PRICE_CIS_RUB=899
PLG_PRICE_INTL_USD_CENTS=1499
PLG_BILLING_RETURN_URL=https://pluginflp.app/billing/return

PLG_APP_VERSION=1.0.0
PLG_MIN_CLIENT_VERSION=1.0.0

PLG_ENV=development
PLG_CAPTCHA_PROVIDER=none
PLG_REQUIRE_DEVICE_BINDING=true

PLG_LEGAL_TERMS_VERSION=1.0
PLG_LEGAL_PRIVACY_VERSION=1.0
PLG_LEGAL_MIN_AGE=16
PLG_SUPPORT_EMAIL=support@pluginflp.app
"@
Set-Content -Path $cloudEnv -Value $cloudContent -Encoding utf8
Write-Host "Wrote cloud\.env" -ForegroundColor Green

# --- patch root .env cloud block ---
if (-not (Test-Path $rootEnv)) {
    Write-Host "WARNING: root .env not found — create it manually." -ForegroundColor Yellow
} else {
    $lines = Get-Content $rootEnv
    $out = New-Object System.Collections.Generic.List[string]
    $inCloud = $false
    $cloudDone = $false

    $cloudBlock = @(
        "# --- Cloud mode (Phase 1 — subscription, server-side AI) ---",
        "PLG_CLOUD_MODE=true",
        "PLG_CLOUD_URL=http://127.0.0.1:8787",
        "SUPABASE_URL=$url",
        "SUPABASE_ANON_KEY=$anon",
        "PLG_ENV=development"
    )

    foreach ($line in $lines) {
        if ($line -match 'Cloud mode') {
            $inCloud = $true
            if (-not $cloudDone) {
                foreach ($b in $cloudBlock) { $out.Add($b) }
                $cloudDone = $true
            }
            continue
        }
        if ($inCloud) {
            if ($line -match '^\s*(PLG_CLOUD_|SUPABASE_|PLG_ENV=)' -or ($line -match '^\s*---' -and $line -notmatch 'Crash')) {
                continue
            }
            if ($line -match '^\s*#' -or $line.Trim() -eq "") {
                $inCloud = $false
            } else {
                $inCloud = $false
            }
        }
        if (-not ($line -match '^\s*(PLG_CLOUD_MODE|PLG_CLOUD_URL|SUPABASE_URL|SUPABASE_ANON_KEY|PLG_ENV=)')) {
            $out.Add($line)
        }
    }

    if (-not $cloudDone) {
        $out.Add("")
        foreach ($b in $cloudBlock) { $out.Add($b) }
    }

    Set-Content -Path $rootEnv -Value $out -Encoding utf8
    Write-Host "Updated root .env (cloud block)" -ForegroundColor Green
}

Write-Host ""
Write-Host "Verifying connection..." -ForegroundColor Cyan
$env:SUPABASE_URL = $url
$env:SUPABASE_ANON_KEY = $anon
$env:SUPABASE_SERVICE_KEY = $service
$env:SUPABASE_JWT_SECRET = $jwt
python (Join-Path $Root "scripts\verify_supabase.py")
if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "Fix errors above, then re-run this script or verify manually." -ForegroundColor Red
    exit $LASTEXITCODE
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Green
Write-Host "  1. pip install -r cloud\requirements.txt"
Write-Host "  2. python cloud\run.py          (API on :8787)"
Write-Host "  3. Restart run_plg.bat        (login screen → full Account page)"
Write-Host ""
